# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-06 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
