# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-12 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_buy_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
